printConfig = true

[logging]
tracelogging = true
logfile = "log/geoip.log"
[logging.http]
enabled = true
stdout = true
fileout = true
logfile = "log/geoip_http.log"

[http]
port = "8081"
host = "localhost"
useHttps = false
tlsMinVersion = "1.2"
httpTLSStrictCiphers = false
tlsCert = "etc/example.crt"
tlsKey = "etc/example.key"
enableCORS = true
jwtSecret = "There is a mouse in my house"

[geoip]
RefreshDuration = "24h" #Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
accountId = "1234"
DatabaseDirectory = "data/geoip"
DatabaseName = "GeoLite2-City.mmdb"
LicenseKey = "testing"

[influxdb]
url = "http://localhost:8086"
token = ""
org = "zone21"
bucket = "kahn"
