printConfig = true

[logging]
tracelogging = true
logfile = "/var/log/geoip/geoip.log"
[logging.http]
enabled = true
stdout = true
fileout = false
logfile = "/var/log/geoip/geoip_http.log"

[http]
host = "localhost"
port = "8081"
useHttps = false
tlsMinVersion = "1.2"
httpTLSStrictCiphers = false
tlsCert = "/etc/ssl/geoip.crt"
tlsKey = "/etc/ssl/geoip.key"
enableCORS = false
jwtSecret = "There is a mouse in my house"

[geoip]
RefreshDuration = "24h"
accountId = 123
DatabaseDirectory = "data/geoip"
DatabaseName = "GeoLite2-City.mmdb"
LicenseKey = "testing"
Verbose = false

[influxdb]
url = "http://localhost:8086"
token = "mytoken"
org = "myOrg"
bucket = "myBucket"
